name: maintenance

on:
  schedule:
    - cron: '0 8 * * 1'  # chaque lundi à 8h UTC
  workflow_dispatch:      # déclenchement manuel possible

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-links:
    uses: ./.github/workflows/reusable-maintenance.yml
