name: reusable-devcontainer-test

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Run task test in the dx devcontainer
        uses: devcontainers/ci@513af61f4de4f75d37e4438f184ba4358f0fc1ca # v0.3.1900000450
        with:
          configFile: .devcontainer/devcontainer.json
          push: never
          runCmd: task test
