name: validate

on:
  pull_request:
    paths-ignore:
      - docs/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    uses: ./.github/workflows/reusable-validate.yml
    secrets: inherit

  test:
    uses: ./.github/workflows/reusable-devcontainer-test.yml
    secrets: inherit

  feature-test:
    uses: ./.github/workflows/reusable-feature-test.yml
    secrets: inherit
